import { NextResponse } from 'next/server';
import { getAnalyticsAggregate } from '@/lib/gcs';

// Force dynamic route
export const dynamic = 'force-dynamic';

// Cache for 5 minutes (aggregate is regenerated after every 6-hour collection)
export const revalidate = 300;

/**
 * GET /api/snapshot
 * Return the pre-computed analytics aggregate generated by aggregate.py
 */
export async function GET() {
  try {
    console.log('Fetching pre-computed analytics aggregate...');

    const aggregate = await getAnalyticsAggregate();

    console.log(
      `Aggregate: ${aggregate.team_metrics.length} teams, ` +
      `${aggregate.workspace_metrics.length} workspaces, ` +
      `${aggregate.daily_engagement.length} engagement days`
    );

    return NextResponse.json(aggregate, {
      status: 200,
      headers: {
        'Cache-Control': 'public, s-maxage=300, stale-while-revalidate=60',
      },
    });
  } catch (error) {
    console.error('Error fetching analytics aggregate:', error);

    return NextResponse.json(
      {
        error: 'Failed to fetch analytics data',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
