import { Storage } from '@google-cloud/storage';
import type { AnalyticsSnapshot } from './types';

const projectId = process.env.GCP_PROJECT_ID || 'coderd';
const bucketName = process.env.GCS_BUCKET_NAME || 'coder-analytics-snapshots';

// Initialize GCS client
const storage = new Storage({
  projectId,
});

const bucket = storage.bucket(bucketName);

/**
 * Fetch the pre-computed analytics aggregate from GCS.
 * Generated by coder/analytics/aggregate.py after each collection run.
 */
export async function getAnalyticsAggregate(): Promise<AnalyticsSnapshot> {
  try {
    const file = bucket.file('analytics_aggregate.json');

    const [exists] = await file.exists();
    if (!exists) {
      throw new Error('analytics_aggregate.json not found. Run coder/analytics/aggregate.py to generate it.');
    }

    const [contents] = await file.download();
    return JSON.parse(contents.toString()) as AnalyticsSnapshot;
  } catch (error) {
    console.error('Error fetching analytics aggregate from GCS:', error);
    throw new Error(`Failed to fetch analytics aggregate: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}
